imports:
    - { resource: user/command_bus.yml }
    - { resource: user/doctrine.yml }
    - { resource: user/fixtures.yml }
    - { resource: user/query_bus.yml }
    - { resource: user/services.yml }
