services:
    app.user.controller.sign_up:
        class: App\User\UI\Http\Rest\SignUp
        arguments:
            - '@app.command.bus'
            - '@app.user.uuid_generator'
        tags:
            - controller.service_arguments
