# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    
imports:
    - { resource: modules/shared.yml }
    - { resource: modules/user.yml }

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: false      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        
    app.command.bus:
        alias: 'command.bus'
        
    app.query.bus:
        alias: 'query.bus'
        
    app.event.bus:
        alias: 'event.bus'
        
    _instanceof:
        # all services implementing the CommandHandlerInterface
        # will be registered on the command.bus bus
        App\Shared\Application\Command\Handler:
            tags:
                - { name: messenger.message_handler, bus: command.bus }
        
        # while those implementing QueryHandlerInterface will be
        # registered on the query.bus bus
        App\Shared\Application\Query\Handler:
            tags:
                - { name: messenger.message_handler, bus: query.bus }

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
#    App\:
#        resource: '../src/'
#        exclude:
#            - '../src/DependencyInjection/'
#            - '../src/Entity/'
#            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
